using Microsoft.AspNetCore.Mvc;
using TrabajoN4.Models;
using System.Collections.Generic;
using System.Linq;

namespace TrabajoN4.Controllers
{
    public class PerrosController : Controller
    {
        private static List<Mascota> perros = new List<Mascota>
        {
            new Mascota { Id = 1, Nombre = "Gran Danés", Descripcion = "Raza gigante, muy amigable.", ImagenUrl = "/images/gran-danes.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 54, Caracteristicas = "Altura impresionante, musculoso y elegante.", Cualidades = "Cariñoso con la familia, protector.", Cuidados = "Ejercicio moderado y revisiones de salud frecuentes." },
            new Mascota { Id = 2,Nombre = "Chihuahua", Descripcion = "Pequeño pero valiente.", ImagenUrl = "/images/chihuahua.jpg", Genero = "Ambos", Tamaño = "Pequeño", Peso = 2, Caracteristicas = "Orejas grandes, vivaz y atento.", Cualidades = "Leal, alerta y protector.", Cuidados = "Evitar climas fríos, ejercicio ligero." },
            new Mascota { Id = 3,Nombre = "Schnauzer", Descripcion = "Energético y leal.", ImagenUrl = "/images/schnauzer.jpg", Genero = "Ambos", Tamaño = "Mediano", Peso = 15, Caracteristicas = "Bigote distintivo, pelaje áspero.", Cualidades = "Valiente, afectuoso y vigilante.", Cuidados = "Cepillado frecuente y actividad diaria." },
            new Mascota { Id = 4,Nombre = "Border Collie", Descripcion = "Inteligente y trabajador.", ImagenUrl = "/images/border-collie.jpg", Genero = "Ambos", Tamaño = "Mediano", Peso = 18, Caracteristicas = "Muy enérgico, pelaje denso.", Cualidades = "Extremadamente inteligente, obediente.", Cuidados = "Mucho ejercicio y estimulación mental." },
            new Mascota { Id = 5,Nombre = "Labrador Retriever", Descripcion = "Amigable, activo y leal.", ImagenUrl = "/images/labrador.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 30, Caracteristicas = "Pelaje corto, gran nadador.", Cualidades = "Sociable, buen compañero de familia.", Cuidados = "Ejercicio diario y alimentación balanceada." },
            new Mascota { Id = 6,Nombre = "Golden Retriever", Descripcion = "Cariñoso, obediente y sociable.", ImagenUrl = "/images/golden-retriever.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 32, Caracteristicas = "Pelaje dorado y sedoso.", Cualidades = "Tierno, buen perro guía.", Cuidados = "Cepillado regular y actividad física." },
            new Mascota { Id = 7,Nombre = "Pastor Alemán", Descripcion = "Protector, inteligente y trabajador.", ImagenUrl = "/images/pastor-aleman.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 35, Caracteristicas = "Musculoso, hocico largo.", Cualidades = "Leal, obediente y protector.", Cuidados = "Entrenamiento constante y ejercicio." },
            new Mascota { Id = 8,Nombre = "Beagle", Descripcion = "Curioso, alegre y afectuoso.", ImagenUrl = "/images/beagle.jpg", Genero = "Ambos", Tamaño = "Mediano", Peso = 10, Caracteristicas = "Orejas largas, olfato excelente.", Cualidades = "Juguetón y amigable.", Cuidados = "Mucho paseo y estimulación olfativa." },
            new Mascota { Id = 9,Nombre = "Bulldog Inglés", Descripcion = "Tranquilo, valiente y cariñoso.", ImagenUrl = "/images/bulldog-ingles.jpg", Genero = "Ambos", Tamaño = "Mediano", Peso = 23, Caracteristicas = "Cuerpo robusto, cara arrugada.", Cualidades = "Amable, protector de niños.", Cuidados = "Cuidado en climas calurosos." },
            new Mascota { Id = 10,Nombre = "Pug", Descripcion = "Encantador, juguetón y tranquilo.", ImagenUrl = "/images/pug.jpg", Genero = "Ambos", Tamaño = "Pequeño", Peso = 7, Caracteristicas = "Cara chata, cola enroscada.", Cualidades = "Sociable y gracioso.", Cuidados = "Evitar calor extremo, control de peso." },
            new Mascota { Id = 11,Nombre = "Rottweiler", Descripcion = "Valiente, leal y protector.", ImagenUrl = "/images/rottweiler.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 50, Caracteristicas = "Musculoso y poderoso.", Cualidades = "Protector, buen guardián.", Cuidados = "Adiestramiento firme y ejercicio." },
            new Mascota { Id = 12,Nombre = "Husky Siberiano", Descripcion = "Enérgico, sociable y aventurero.", ImagenUrl = "/images/husky.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 25, Caracteristicas = "Ojos claros, pelaje espeso.", Cualidades = "Resistente y amigable.", Cuidados = "Mucho ejercicio y climas fríos." },
            new Mascota { Id = 13,Nombre = "Dálmata", Descripcion = "Activo, sociable y elegante.", ImagenUrl = "/images/dalmata.jpg", Genero = "Ambos", Tamaño = "Mediano", Peso = 24, Caracteristicas = "Manchas negras o marrones.", Cualidades = "Juguetón, buen compañero.", Cuidados = "Ejercicio diario y cuidado del pelaje." },
            new Mascota { Id = 14,Nombre = "Shih Tzu", Descripcion = "Cariñoso, tranquilo y elegante.", ImagenUrl = "/images/shih-tzu.jpg", Genero = "Ambos", Tamaño = "Pequeño", Peso = 6, Caracteristicas = "Pelaje largo y sedoso.", Cualidades = "Afectuoso, excelente en interiores.", Cuidados = "Cepillado diario y baños regulares." },
            new Mascota { Id = 15,Nombre = "Bóxer", Descripcion = "Protector, activo y amigable.", ImagenUrl = "/images/boxer.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 30, Caracteristicas = "Musculoso y ágil.", Cualidades = "Leal y juguetón.", Cuidados = "Ejercicio moderado y socialización." },
            new Mascota { Id = 16,Nombre = "Akita Inu", Descripcion = "Fiel, reservado y protector.", ImagenUrl = "/images/akita.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 45, Caracteristicas = "Pelaje espeso, porte digno.", Cualidades = "Independiente y protector.", Cuidados = "Entrenamiento desde cachorro." },
            new Mascota { Id = 17,Nombre = "Cocker Spaniel", Descripcion = "Dulce, sociable y enérgico.", ImagenUrl = "/images/cocker.jpg", Genero = "Ambos", Tamaño = "Mediano", Peso = 12, Caracteristicas = "Orejas largas, pelaje ondulado.", Cualidades = "Cariñoso y alegre.", Cuidados = "Cepillado frecuente y paseos diarios." },
            new Mascota { Id = 18,Nombre = "Maltés", Descripcion = "Pequeño, afectuoso y vivaz.", ImagenUrl = "/images/maltes.jpg", Genero = "Ambos", Tamaño = "Pequeño", Peso = 4, Caracteristicas = "Pelaje blanco largo.", Cualidades = "Alegre y amigable.", Cuidados = "Cepillado diario y limpieza ocular." },
            new Mascota { Id = 19,Nombre = "Doberman", Descripcion = "Valiente, protector y leal.", ImagenUrl = "/images/doberman.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 40, Caracteristicas = "Elegante y musculoso.", Cualidades = "Alerta y protector.", Cuidados = "Entrenamiento firme y actividad física." },
            new Mascota { Id = 20,Nombre = "Samoyedo", Descripcion = "Alegre y enérgico.", ImagenUrl = "/images/samoyedo.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 25, Caracteristicas = "Pelaje blanco y esponjoso.", Cualidades = "Sociable y afectuoso.", Cuidados = "Cepillado diario y ejercicio." },
            new Mascota { Id = 21,Nombre = "San Bernardo", Descripcion = "Gentil gigante.", ImagenUrl = "/images/san-bernardo.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 70, Caracteristicas = "Masivo, pelaje denso.", Cualidades = "Calmado y protector.", Cuidados = "Espacio amplio y cuidado del pelaje." },
            new Mascota { Id = 22,Nombre = "Basset Hound", Descripcion = "Tranquilo y fiel.", ImagenUrl = "/images/basset-hound.jpg", Genero = "Ambos", Tamaño = "Mediano", Peso = 27, Caracteristicas = "Orejas largas, patas cortas.", Cualidades = "Buen olfato y sociable.", Cuidados = "Caminatas diarias y limpieza de orejas." },
            new Mascota { Id = 23,Nombre = "Galgo", Descripcion = "Ágil y rápido.", ImagenUrl = "/images/galgo.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 30, Caracteristicas = "Cuerpo esbelto, musculoso.", Cualidades = "Dócil y veloz.", Cuidados = "Carreras cortas y suaves." },
            new Mascota { Id = 24,Nombre = "Boston Terrier", Descripcion = "Juguetón y elegante.", ImagenUrl = "/images/boston-terrier.jpg", Genero = "Ambos", Tamaño = "Pequeño", Peso = 9, Caracteristicas = "Pelaje corto, cara simpática.", Cualidades = "Amigable y curioso.", Cuidados = "Ejercicio moderado." },
            new Mascota { Id = 25,Nombre = "Fox Terrier", Descripcion = "Valiente y activo.", ImagenUrl = "/images/fox-terrier.jpg", Genero = "Ambos", Tamaño = "Mediano", Peso = 8, Caracteristicas = "Pelaje duro o liso.", Cualidades = "Enérgico y vigilante.", Cuidados = "Ejercicio y juegos." },
            new Mascota { Id = 26,Nombre = "Shiba Inu", Descripcion = "Independiente y ágil.", ImagenUrl = "/images/shiba-inu.jpg", Genero = "Ambos", Tamaño = "Mediano", Peso = 10, Caracteristicas = "Cola rizada, pelaje rojo.", Cualidades = "Limpio y leal.", Cuidados = "Ejercicio moderado." },
            new Mascota { Id = 27,Nombre = "Yorkshire Terrier", Descripcion = "Pequeño y elegante.", ImagenUrl = "/images/yorkshire.jpg", Genero = "Ambos", Tamaño = "Pequeño", Peso = 3, Caracteristicas = "Pelaje largo y sedoso.", Cualidades = "Valiente y cariñoso.", Cuidados = "Cepillado frecuente." },
            new Mascota { Id = 28,Nombre = "Caniche", Descripcion = "Inteligente y versátil.", ImagenUrl = "/images/caniche.jpg", Genero = "Ambos", Tamaño = "Mediano", Peso = 12, Caracteristicas = "Pelaje rizado.", Cualidades = "Sociable y ágil.", Cuidados = "Cepillado y cortes regulares." },
            new Mascota { Id = 29,Nombre = "Pastor Australiano", Descripcion = "Activo y trabajador.", ImagenUrl = "/images/pastor-australiano.jpg", Genero = "Ambos", Tamaño = "Mediano", Peso = 25, Caracteristicas = "Pelaje tricolor o merlé.", Cualidades = "Inteligente y leal.", Cuidados = "Mucho ejercicio." },
            new Mascota { Id = 30,Nombre = "Akita Americano", Descripcion = "Digno y fuerte.", ImagenUrl = "/images/akita-americano.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 50, Caracteristicas = "Musculoso y robusto.", Cualidades = "Protector y leal.", Cuidados = "Entrenamiento firme." },
            new Mascota { Id = 31,Nombre = "Terranova", Descripcion = "Gentil y fuerte nadador.", ImagenUrl = "/images/terranova.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 60, Caracteristicas = "Pelaje espeso y resistente al agua.", Cualidades = "Afectuoso y protector.", Cuidados = "Espacio amplio y natación." },
            new Mascota { Id = 32,Nombre = "Bulldog Francés", Descripcion = "Pequeño y encantador.", ImagenUrl = "/images/bulldog-frances.jpg", Genero = "Ambos", Tamaño = "Pequeño", Peso = 11, Caracteristicas = "Orejas de murciélago.", Cualidades = "Juguetón y sociable.", Cuidados = "Evitar climas calurosos." },
            new Mascota { Id = 33,Nombre = "Whippet", Descripcion = "Rápido y elegante.", ImagenUrl = "/images/whippet.jpg", Genero = "Ambos", Tamaño = "Mediano", Peso = 14, Caracteristicas = "Esbelto y atlético.", Cualidades = "Dócil y cariñoso.", Cuidados = "Ejercicio moderado." },
            new Mascota { Id = 34,Nombre = "Perro de Agua Español", Descripcion = "Versátil y trabajador.", ImagenUrl = "/images/perro-agua.jpg", Genero = "Ambos", Tamaño = "Mediano", Peso = 20, Caracteristicas = "Pelaje rizado.", Cualidades = "Leal y activo.", Cuidados = "Cepillado y ejercicio." },
            new Mascota { Id = 35,Nombre = "Mastín Español", Descripcion = "Imponente y protector.", ImagenUrl = "/images/mastin.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 70, Caracteristicas = "Gran tamaño, fuerte.", Cualidades = "Calmado y vigilante.", Cuidados = "Espacio amplio." },
            new Mascota { Id = 36,Nombre = "Basenji", Descripcion = "Silencioso y ágil.", ImagenUrl = "/images/basenji.jpg", Genero = "Ambos", Tamaño = "Pequeño", Peso = 9, Caracteristicas = "No ladra, pelaje corto.", Cualidades = "Curioso y limpio.", Cuidados = "Ejercicio y compañía." },
            new Mascota { Id = 37,Nombre = "Corgi Galés", Descripcion = "Bajo y simpático.", ImagenUrl = "/images/corgi.jpg", Genero = "Ambos", Tamaño = "Pequeño", Peso = 12, Caracteristicas = "Patas cortas, cola corta.", Cualidades = "Alegre y leal.", Cuidados = "Ejercicio moderado." },
            new Mascota { Id = 38,Nombre = "Spitz Alemán", Descripcion = "Vivaz y elegante.", ImagenUrl = "/images/spitz.jpg", Genero = "Ambos", Tamaño = "Pequeño", Peso = 7, Caracteristicas = "Pelaje esponjoso.", Cualidades = "Alerta y fiel.", Cuidados = "Cepillado frecuente." },
            new Mascota { Id = 39,Nombre = "Pointer", Descripcion = "Atento y rápido.", ImagenUrl = "/images/pointer.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 28, Caracteristicas = "Atlético y elegante.", Cualidades = "Buen cazador y amigable.", Cuidados = "Ejercicio diario." },
            new Mascota { Id = 40,Nombre = "Setter Irlandés", Descripcion = "Alegre y elegante.", ImagenUrl = "/images/setter-irlandes.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 32, Caracteristicas = "Pelaje rojo sedoso.", Cualidades = "Sociable y activo.", Cuidados = "Mucho ejercicio." },
            new Mascota { Id = 41,Nombre = "Weimaraner", Descripcion = "Atlético y leal.", ImagenUrl = "/images/weimaraner.jpg", Genero = "Ambos", Tamaño = "Grande", Peso = 34, Caracteristicas = "Pelaje gris plateado.", Cualidades = "Inteligente y activo.", Cuidados = "Ejercicio intenso." }
        };

        public IActionResult Index()
        {
            return View(perros);
        }

        public IActionResult Detalles(int id)
        {
            var perro = perros.FirstOrDefault(p => p.Id == id);
            if (perro == null) return NotFound();
            return View(perro);
        }
    }
}
